spring.application.name=chatapp

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/chatapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=ResetPassword123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
app.jwt.secret=9a76a982ba342e47206148386127218671827461284762184712864817264812
app.jwt.expirationMs=86400000
